sudo: required

notifications:
  email: false

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t "$DOCKER_USERNAME/finalword" .
  - docker push "$DOCKER_USERNAME/finalword"
